name: 'Build Jupyterbook'
description: 'Build the Jupyterbook with desired run features'

inputs:
  jb-cache:
    description: “Set up the Jupyterbook Cache (boolean)”
    required: true
  publish-to-gh:
    description: “Publish to GitHub Pages (boolean)”
    required: true
  jb-save:
    description: "Save the Jupyterbook Build (boolean)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup JupyterBook Cache
      if: ${{inputs.jb-cache}} == true
      uses: actions/cache@v2
      with:
        path: ./book/_build
        # NOTE: change key to "jupyterbook-N+1" to force rebuilding cache
        key: jupyterbook-0

    - uses: ./.github/actions/setupconda

    - name: Build JupyterBook
      run: |
        jb build book

    - name: Publish to GitHub Pages
      if: ${{inputs.publish-to-gh}} == true
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: book/_build/html
        publish_branch: gh-pages

    - name: Save Build
      if: ${{inputs.jb-save}} == true}} and ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: book/_build/
