name: Cron

on:
  schedule:
    # run this once a week (sunday midnight) to preserve cache
    # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
    - cron:  '0 0 * * 0'

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - uses: ./.github/actions/buildbook
      with:
        jb-cache: true
        publish-to-gh: false
        jb-save: true
