name: Cron

on:
  schedule:
    # run this once a week (sunday midnight) to preserve cache
    # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
    - cron:  '0 0 * * 0'

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup JupyterBook Cache
      uses: actions/cache@v2
      # NOTE: change key to "jupyterbook-N+1" to force rebuilding cache
      with:
        path: ./book/_build
        key: jupyterbook

    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('binder/conda-linux-64.lock') }}

    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        auto-update-conda: false
        environment-file: binder/conda-linux-64.lock #or binder/environment.yml
        activate-environment: hackweek
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: github-actions-role
        role-duration-seconds: 1800

    - name: Build JupyterBook
      env:
        EARTHDATA_LOGIN: ${{ secrets.EARTHDATA_LOGIN }}
        EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
      run: |
        jb build book

    - name: Save Build
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: book/_build/
