name: NetlifyPreview

on:
  pull_request_target:
    types: [labeled]

jobs:
  add-preview:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    # This workflow accesses secrets and checks out a PR, so only run if labelled
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    if: contains(github.event.pull_request.labels.*.name, 'preview')

    steps:
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('binder/conda-linux-64.lock') }}

    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        auto-update-conda: false
        environment-file: binder/conda-linux-64.lock #or binder/environment.yml
        activate-environment: hackweek
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: Setup JupyterBook Cache
      uses: actions/cache@v2
      # NOTE: change key to "jupyterbook-N+1" to force rebuilding cache
      with:
        path: ./book/_build
        key: jupyterbook

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: github-actions-role
        role-duration-seconds: 1800

    - name: Build JupyterBook
      env:
        # Warning: careful exposing secrets in scripts
        EARTHDATA_LOGIN: ${{ secrets.EARTHDATA_LOGIN }}
        EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
      run: |
        jb build book

    - name: Deploy Website Preview
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './book/_build/html'
        production-deploy: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-commit-comment: false
        enable-pull-request-comment: true
        overwrites-pull-request-comment: true
        alias: deploy-preview-${{ github.event.number }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1
